name: radwave
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas=1.5.3
  - scipy
  - matplotlib
  - netCDF4
  - matplotlib
  - numpy
  - scikit-image
  - shapely
  - cftime
  - jupyter
  - ipython
  - seaborn
  - geopy
  - cartopy
  - pip:
    - cmocean
    - pymannkendall
    - radwave
